import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  inboxSidebar: [
    {
      type: 'autogenerated',
      dirName: 'inbox',
    },
  ],
  topCategory1Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'top-category-1',
    },
  ],
  topCategory2Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'top-category-2',
    },
  ],
  topCategory3Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'top-category-3',
    },
  ],
};

export default sidebars;
