import { Fragment, type ReactNode } from 'react';
import useBaseUrl from '@docusaurus/useBaseUrl';
import sidebars from '@site/sidebars';
import categoryNav from '@site/src/data/category-nav.json';
import docTitles from '@site/src/data/doc-titles.json';
import styles from './styles.module.css';

type SidebarItem = {
  type: string;
  dirName?: string;
  label?: string;
  items?: SidebarItem[];
  id?: string;
};

type PageInfo = {
  docId: string;
  title: string;
  position: number;
};

type SubcategoryInfo = {
  key: string;
  title: string;
  docId: string;
  hasIndex: boolean;
  position: number;
  pages: PageInfo[];
};

type CategoryData = {
  pages: PageInfo[];
  subcategories: SubcategoryInfo[];
};

/**
 * Convert a doc ID to a proper Docusaurus URL path.
 * Docusaurus routes index docs to the parent directory URL,
 * e.g. "overview/index" -> "overview", not "overview/index".
 */
function docIdToUrl(docsBaseUrl: string, docId: string): string {
  const path = docId.replace(/\/index$/, '');
  return `${docsBaseUrl}${path}`;
}

function generateLabel(sidebarId: string): string {
  return sidebarId
    .replace(/Sidebar$/i, '')
    .replace(/([A-Z])/g, ' $1')
    .trim()
    .toUpperCase();
}

function renderCategoryNavData(
  catData: CategoryData,
  docsBaseUrl: string,
): ReactNode {
  return (
    <Fragment>
      {catData.pages.length > 0 && (
        <ul className={styles.pageList}>
          {catData.pages.map((page) => (
            <li key={page.docId}>
              <a href={docIdToUrl(docsBaseUrl, page.docId)}>{page.title}</a>
            </li>
          ))}
        </ul>
      )}
      {catData.subcategories.map((sub) => (
        <div key={sub.key} className={styles.subcategory}>
          <h4 className={styles.subcategoryTitle}>
            {sub.hasIndex ? (
              <a href={docIdToUrl(docsBaseUrl, sub.docId)}>{sub.title}</a>
            ) : (
              sub.title
            )}
          </h4>
          {sub.pages.length > 0 && (
            <ul className={styles.pageList}>
              {sub.pages.map((page) => (
                <li key={page.docId}>
                  <a href={docIdToUrl(docsBaseUrl, page.docId)}>{page.title}</a>
                </li>
              ))}
            </ul>
          )}
        </div>
      ))}
    </Fragment>
  );
}

function renderAutogenerated(
  dirName: string,
  docsBaseUrl: string,
): ReactNode {
  if (dirName === '.') {
    // Root level - render all categories
    const categoryKeys = Object.keys(categoryNav as Record<string, CategoryData>);
    if (categoryKeys.length === 0) {
      return <p className={styles.empty}>No documents found.</p>;
    }

    // Also render root-level pages from doc-titles that don't belong to any category
    const rootPages: Array<{ docId: string; title: string }> = [];
    const titles = docTitles as Record<string, string>;
    for (const [docId, title] of Object.entries(titles)) {
      if (!docId.includes('/')) {
        rootPages.push({ docId, title });
      }
    }

    return (
      <Fragment>
        {rootPages.length > 0 && (
          <ul className={styles.pageList}>
            {rootPages.map((page) => (
              <li key={page.docId}>
                <a href={docIdToUrl(docsBaseUrl, page.docId)}>{page.title}</a>
              </li>
            ))}
          </ul>
        )}
        {categoryKeys.map((catKey) => {
          const catData = (categoryNav as Record<string, CategoryData>)[catKey];
          return (
            <div key={catKey} className={styles.categorySection}>
              <h3 className={styles.categoryTitle}>{catKey}</h3>
              {renderCategoryNavData(catData, docsBaseUrl)}
            </div>
          );
        })}
      </Fragment>
    );
  }

  // Specific directory
  const catData = (categoryNav as Record<string, CategoryData>)[dirName];
  if (catData) {
    return renderCategoryNavData(catData, docsBaseUrl);
  }

  // Fallback to doc-titles
  const titles = docTitles as Record<string, string>;
  const matchingDocs = Object.entries(titles).filter(
    ([docId]) => docId.startsWith(`${dirName}/`) && docId !== `${dirName}/index`,
  );

  if (matchingDocs.length === 0) {
    return <p className={styles.empty}>No documents found.</p>;
  }

  return (
    <ul className={styles.pageList}>
      {matchingDocs.map(([docId, title]) => (
        <li key={docId}>
          <a href={docIdToUrl(docsBaseUrl, docId)}>{title}</a>
        </li>
      ))}
    </ul>
  );
}

function renderSidebarItems(
  items: SidebarItem[],
  docsBaseUrl: string,
): ReactNode {
  return (
    <Fragment>
      {items.map((item, idx) => {
        if (item.type === 'autogenerated') {
          return (
            <Fragment key={`auto-${idx}`}>
              {renderAutogenerated(item.dirName || '.', docsBaseUrl)}
            </Fragment>
          );
        }
        if (item.type === 'category' && item.items) {
          return (
            <div key={`cat-${idx}`} className={styles.categorySection}>
              <h3 className={styles.categoryTitle}>{item.label || 'Category'}</h3>
              {renderSidebarItems(item.items, docsBaseUrl)}
            </div>
          );
        }
        if (item.type === 'doc' && item.id) {
          const titles = docTitles as Record<string, string>;
          const title = titles[item.id] || item.label || item.id;
          return (
            <ul key={`doc-${idx}`} className={styles.pageList}>
              <li>
                <a href={docIdToUrl(docsBaseUrl, item.id)}>{title}</a>
              </li>
            </ul>
          );
        }
        if (typeof item === 'string') {
          const titles = docTitles as Record<string, string>;
          const title = titles[item] || item;
          return (
            <ul key={`str-${idx}`} className={styles.pageList}>
              <li>
                <a href={docIdToUrl(docsBaseUrl, item)}>{title}</a>
              </li>
            </ul>
          );
        }
        return null;
      })}
    </Fragment>
  );
}

export default function DocsSitemap(): ReactNode {
  const docsBaseUrl = useBaseUrl('/docs/');
  const sidebarEntries = Object.entries(sidebars) as Array<[string, SidebarItem[]]>;

  return (
    <div className={styles.sitemap}>
      {sidebarEntries.map(([sidebarId, items]) => (
        <details key={sidebarId} className={styles.sidebarSection} open>
          <summary className={styles.sidebarTitle}>
            <span className={styles.chevron}>&#9654;</span>
            {generateLabel(sidebarId)}
          </summary>
          <div className={styles.sidebarContent}>
            {Array.isArray(items) ? renderSidebarItems(items, docsBaseUrl) : null}
          </div>
        </details>
      ))}
    </div>
  );
}
